In [ ]:
# conda install conda-forge::bpemb
from bpemb import BPEmb
bpemb_en = BPEmb(
    lang="en",
    vs=10000,
    dim=100,
    cache_dir="data",
    model_file="../../data/bpemb/bpemb.model",
    emb_file="../../data/bpemb/bpemb_vectors.txt"
)


In [4]:
print(bpemb_en.vectors[bpemb_en.words.index('car')])


[-0.305548 -0.325598 -0.134716 -0.078735 -0.660545  0.076211 -0.735487
  0.124533 -0.294402  0.459688  0.030137  0.174041 -0.224223  0.486189
 -0.504649 -0.459699  0.315747  0.477885  0.091398  0.427867  0.016524
 -0.076833 -0.899727  0.493158 -0.022309 -0.422785 -0.154148  0.204981
  0.379834  0.070588  0.196073 -0.368222  0.473406  0.007409  0.004303
 -0.007823 -0.19103  -0.202509  0.109878 -0.224521 -0.35741  -0.611633
  0.329958 -0.212956 -0.497499 -0.393839 -0.130101 -0.216903 -0.105595
 -0.076007 -0.483942 -0.139704 -0.161647  0.136985  0.415363 -0.360143
  0.038601 -0.078804 -0.030421  0.324129  0.223378 -0.523636 -0.048317
 -0.032248 -0.117367  0.470519  0.225816 -0.222065 -0.225007 -0.165904
 -0.334389 -0.20157   0.572352 -0.268794  0.301929 -0.005563  0.387491
  0.261031 -0.11613   0.074982 -0.008433  0.259987 -0.099893 -0.268875
 -0.054047 -0.534776 -0.111101 -0.051742  0.214114  0.04293   0.039873
 -0.453112  0.087382 -0.333201 -0.034079 -0.833045  0.155232 -1.132393
 -0.29

In [16]:
sample_sentence = "Where can I find a pizzeria?"
tokens = bpemb_en.encode(sample_sentence)
print(tokens)

import torch
device = 'cpu'
token_seq = torch.tensor(bpemb_en.encode_ids("Where can I find a pizzeria?")).to(device)
print(token_seq)

['▁where', '▁can', '▁i', '▁find', '▁a', '▁p', 'iz', 'zer', 'ia', '?']
tensor([ 571,  280,  386, 1934,    4,   24,  248, 4339,  177, 9967])


In [18]:
bpemb_vocab_size, bpemb_embed_size = bpemb_en.vectors.shape
embed_dim = 12
token_embedding = torch.nn.Embedding(bpemb_vocab_size, embed_dim).to(device)
token_embeddings = token_embedding(token_seq)

# The untrained embeddings for our sample sentence.
print("Embeddings for: ", sample_sentence)
print(token_embeddings)

Embeddings for:  Where can I find a pizzeria?
tensor([[-8.7463e-01, -8.9760e-01, -1.3411e-01, -6.6376e-01,  9.1327e-01,
         -1.3950e+00, -6.0384e-01,  1.8610e+00,  5.9130e-03,  9.7661e-01,
          3.1923e-01,  1.2676e+00],
        [ 1.1055e+00, -1.5845e+00, -4.0840e-01, -1.2682e+00, -1.0185e-01,
         -4.7967e-01,  1.1287e+00, -6.0515e-01, -4.6186e-01,  8.9609e-01,
         -5.7444e-01,  7.9070e-01],
        [ 1.6365e+00, -2.1626e+00, -6.0403e-01, -6.5807e-01,  3.6614e-01,
         -4.9695e-02,  6.8056e-03, -8.7919e-01, -7.7395e-02,  1.0444e-02,
          6.8102e-02, -4.7479e-01],
        [-2.1261e+00,  2.2726e+00, -5.7704e-01,  2.5164e-01, -5.3282e-02,
         -1.2597e+00, -1.1039e+00, -3.8213e-01, -7.2975e-01, -1.3232e-01,
         -1.0422e+00,  1.0553e+00],
        [-1.3604e+00,  7.2590e-01, -1.0385e-01,  1.5275e+00,  3.9906e-02,
          6.4281e-02, -6.3645e-01,  6.0490e-01, -7.3768e-01,  6.5772e-01,
         -1.3318e+00,  1.7726e-01],
        [ 2.0911e-01, -1.3869e+00,

In [19]:
#positional information now
max_seq_len = 256
position_embedding = torch.nn.Embedding(max_seq_len, embed_dim).to(device)

pos_idx = torch.tensor(list(range(len(token_seq)))).to(device)
print(pos_idx)

position_embeddings = position_embedding(pos_idx)
print("Embeddings for: ", sample_sentence)
print(position_embeddings)

input = position_embeddings + token_embeddings

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Embeddings for:  Where can I find a pizzeria?
tensor([[ 0.1246,  0.7973, -1.2678,  0.1535, -2.6879, -1.4674,  1.7158, -0.1523,
         -0.0535, -2.2563,  0.0050,  0.6399],
        [ 0.9518, -0.8789, -0.5462,  0.4181, -0.2060,  0.4292, -0.3480, -0.2873,
         -0.0808, -1.0258, -0.4338,  0.0543],
        [-1.0192,  0.1910,  0.1743, -0.3879,  0.6084, -0.1201, -1.3427,  0.5509,
         -0.2582, -0.3114, -0.8161, -0.7931],
        [-0.5894,  0.2700,  0.2608,  0.4741, -0.9167, -0.1942, -0.5391,  1.1258,
          0.3955, -0.0808,  0.1725, -1.5417],
        [-1.9315, -1.3421,  0.7003, -0.1287, -0.6843, -0.1778,  0.7739, -0.0385,
         -0.1611, -2.2844, -0.7751,  2.8328],
        [ 0.3312,  0.8206,  0.4232, -0.2132, -1.0924,  1.3171, -1.6360,  0.6603,
         -1.3691,  1.5146,  0.8216, -0.3161],
        [ 0.3677, -0.3788, -1.2730,  0.3806,  0.0057,  0.4642,  1.3096, -0.8553,
          2.0010, -0.1971,  1.5171,  0.7705],
        [-0.3760, -1.9196,